apiVersion: v1
kind: Service
metadata:
  name: websocket-poc-service
  labels:
    app: websocket-poc
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: websocket-poc
